version: '3.9'  # Puedes eliminar la versión si tu Docker Compose la soporta

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./ecomm_db_data:/var/lib/postgresql/data
    networks:
      - ecomm-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - '3000:3000'  
    depends_on:
      - db
    command: /wait-for-it.sh db:5432 -- npm run start
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
    networks:
      - ecomm-network

networks:
  ecomm-network:
    driver: bridge  # Solo el driver, sin 'name'

volumes:
  ecomm_db_data:
